# Generated by Django 6.0.3 on 2026-04-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('FixedAsset', 'FixedAsset'), ('Counterparty', 'Counterparty'), ('Departament', 'Departament')], max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(max_length=50, verbose_name='ID сущности')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление'), ('MARK_DELETE', 'Пометка на удаление'), ('CODE_GENERATE', 'Генерация кода'), ('DUPLICATE_CHECK', 'Проверка дубликатов')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание изменения')),
                ('changed_by', models.CharField(default='system', max_length=100, verbose_name='Кто выполнил изменение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('name', models.CharField(help_text='Полное наименование организации или ФИО', max_length=300, verbose_name='Наименование контрагента')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('internal_code', models.AutoField(primary_key=True, serialize=False, verbose_name='Внутренний код')),
                ('deletion_mark', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название подразделения')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код подразделения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование основного средства')),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код внутреннего учета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='contract.departament', verbose_name='Подразделение (место хранения)')),
            ],
            options={
                'verbose_name': 'Основное средство',
                'verbose_name_plural': 'Основные средства',
                'ordering': ['Departament', 'internal_code'],
            },
        ),
    ]
