# Generated by Django 6.0.3 on 2026-04-11 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Сотрудник')),
                ('accrued_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Сумма не может быть отрицательной'), django.core.validators.MaxValueValidator(1000000, message='Сумма не может превышать 1 000 000')], verbose_name='Начислено')),
                ('accrual_date', models.DateField(auto_now_add=True, verbose_name='Дата начисления')),
            ],
            options={
                'verbose_name': 'Начисление зарплаты',
                'verbose_name_plural': 'Начисления зарплаты',
                'db_table': 'employee_salary',
                'ordering': ['-accrual_date', 'name'],
            },
        ),
    ]
