# Generated by Django 6.0.3 on 2026-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ['department', 'name'], 'verbose_name': 'Начисление зарплаты', 'verbose_name_plural': 'Начисления зарплаты'},
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='department',
            field=models.CharField(default='Основное', max_length=100, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='position',
            field=models.CharField(default='Сотрудник', max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='accrual_date',
            field=models.DateField(verbose_name='Дата начисления'),
        ),
    ]
