# Generated by Django 6.0.3 on 2026-04-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('basis', models.TextField(blank=True, verbose_name='Основание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.employee', verbose_name='Сотрудник')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отчета')),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма расхода')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
