# Generated by Django 6.0.3 on 2026-04-12 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Гос.Номер')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Номер расхода (л/км)')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ManyToManyField(blank=True, to='tracking.car', verbose_name='Автомобиль')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('departure_time', models.DateTimeField(verbose_name='Время выезда')),
                ('return_time', models.DateTimeField(verbose_name='Время заезда')),
                ('start_mileage', models.PositiveIntegerField(verbose_name='Начальный километраж')),
                ('end_mileage', models.PositiveIntegerField(verbose_name='Конечный километраж')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.car', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-date', '-departure_time'],
                'unique_together': {('driver', 'date', 'departure_time')},
            },
        ),
    ]
