# Generated by Django 6.0.3 on 2026-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Расход топлива (л/км)'),
        ),
    ]
